server:
  port: 9907
  
spring:
  application:
    name: metcs673-user-maagement-service
    

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/spring_alerts}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWROD:Dby310115}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
