server:
  port: 9982
  
spring:
  application:
    name: metcs673-user-maagement-service
    

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3307/metcs673_um_servivice_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWROD:wizini!87}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

        
okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-v4utikpr1mrs4k05.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: http://localhost:9983