CREATE TABLE UM_USER_TYPE (
  id SERIAL PRIMARY KEY, 
  type VARCHAR(50) NOT NULL UNIQUE, 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE UM_USER (
  id BIGSERIAL PRIMARY KEY, -- 
  identity_provider_id VARCHAR(255) NOT NULL UNIQUE, 
  firstname VARCHAR(200),
  lastname VARCHAR(200),
  email VARCHAR(255) NOT NULL UNIQUE, 
  username VARCHAR(200) UNIQUE, 
  phone VARCHAR(50),
  address VARCHAR(50),
  city VARCHAR(70),
  state VARCHAR(70),
  postal_code VARCHAR(15),
  country VARCHAR(70),
  user_type_id INTEGER REFERENCES UM_USER_TYPE(id), 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS users_user_type_id_foreign ON UM_USER (user_type_id); 

INSERT INTO UM_USER_TYPE (type) VALUES ('ADMIN'), ('STUDENT'), ('INTRUCTOR'), ('ADMINISTRATOR');